/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as subscriberSol from "./Subscriber.sol";
export type { subscriberSol };
import type * as subsicriderSol from "./Subsicrider.sol";
export type { subsicriderSol };
